### ISSUE TITLE
Is it possible to trigger metrics only for selected components/templates?

### ISSUE THREAD

**Issue by wasilak** [kacperus/cf-metrics#6]
Hi,

We are using unit tests and what I want to accomplish is trigger coverage only when someone is running them, not when using simply using application. This is set up on a dev server, where QA team is testing at the same time as unit tests may be run.

Thanks,
Peter

**Comment by kacperus** [comment]
No, it's not possible to enable / disable metrics for only selected sub-set of your application templates. When enabled (deployed) it basically touches every single template. I wouldn't consider it a problem thought as it has really small footprint on the application performance.

There isn't a turn off / on switch neither.
