### ISSUE TITLE
Plans to Support Lucee Engine?

### ISSUE THREAD

**Issue by jamiejackson** [kacperus/cf-metrics#7]
Are there any plans to support Lucee?

**Comment by kacperus** [comment]
Currently not. Unfortunately I don't have much time these days to go back to cf-metrics project (my late reply to your question is excellent prove of that I'm afraid). 

Actually I made some attempts to integrate with Lucee 4+ at the beginning of the year and it looked really promising. Don't expect to see it happen anywhere soon, though...
